# Generated by Django 4.1.3 on 2023-01-07 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_phone_number_userprofile_phone_number'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='vendor',
            name='userprofile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='Perfil de usuario'),
            preserve_default=False,
        ),
    ]
