# Generated by Django 4.1.3 on 2023-01-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_user_alter_vendor_userprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='userprofile',
            new_name='user_profile',
        ),
    ]
