# Generated by Django 4.1.3 on 2023-01-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_rename_userprofile_vendor_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='URL amigable'),
        ),
    ]
