# Generated by Django 4.1.3 on 2023-01-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_category_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vendor',
        ),
    ]
