# Generated by Django 4.1.3 on 2023-01-11 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_rename_userprofile_vendor_user_profile'),
        ('menu', '0003_remove_category_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vendor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor', verbose_name='Vendedor'),
            preserve_default=False,
        ),
    ]
